export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REM_INGREDIENT = 'REM_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERR_INGREDIENTS = 'ERR_INGREDIENTS';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_START = 'PURCHASE_START';
