export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REM_INGREDIENT = 'REM_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ERR_INGREDIENTS = 'ERR_INGREDIENTS';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_RESET = 'PURCHASE_RESET';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOG_OUT = 'LOG_OUT';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
